/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'amit.nahum' at '12/26/17 11:31 AM' with Gradle 3.0
 *
 * @author amit.nahum, @date 12/26/17 11:31 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
